### ISSUE TITLE
Bad webpack config?

### ISSUE THREAD

**Issue by liam-goodacre-hpe** [unional/reactor-typescript-boilerplate#5]
I tried `npm run start` and the following happened:

```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'ts'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, performance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
   For typos: please correct them.
   For loader options: webpack 2 no longer allows custom properties in configuration.
     Loaders should be updated to allow passing options via loader options in module.rules.
     Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
     plugins: [
       new webpack.LoaderOptionsPlugin({
         // test: /\.xxx$/, // may apply this only for some modules
         options: {
           ts: ...
         }
       })
     ]
 - configuration.module has an unknown property 'preLoaders'. These properties are valid:
   object { exprContextCritical?, exprContextRecursive?, exprContextRegExp?, exprContextRequest?, loaders?, noParse?, rules?, unknownContextCritical?, unknownContextRecursive?, unknownContextRegExp?, unknownContextRequest?, unsafeCache?, wrappedContextCritical?, wrappedContextRecursive?, wrappedContextRegExp?, strictExportPresence? }
   Options affecting the normal modules (`NormalModuleFactory`).
 - configuration.resolve.extensions[0] should not be empty.
```

**Comment by unional** [comment]
Thanks. I need to update this project.

**Comment by markbrocato** [comment]
@unional #8 should fix these.

**Comment by liam-goodacre-hpe** [comment]
Running since #8, `npm run start` now fails differently and produces the following output (cleaned up a bit):

```
webpack: Using compiler.parser is deprecated.
Use compiler.plugin("compilation", function(compilation, data) {
  data.normalModuleFactory.plugin("parser", function(parser, options) { parser.plugin(/* ... */); });
}); instead. It was called at ReactExtJSWebpackTSPlugin.apply (...\reactor-typescript-boilerplate\node_modules\reactor-webpack-ts-plugin\dist\index.js:76:25).

10% building modules 1/1 modules 0 active

Project is running at http://localhost:8081/
webpack output is served from /
Content not from webpack is served from ./build
404s will fallback to /index.html

10% building modules 1/4 modules 3 active ...ode_modules\webpack\hot\dev-server.jsts-loader: Using typescript@2.2.2 and ...\reacto
10% building modules 2/4 modules 2 active ...ode_modules\webpack\hot\dev-server.js

(node:10292) DeprecationWarning: loaderUtils.parseQuery() received a non-string
value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.

94% asset optimizationoutputPath: ...\reactor-typescript-boilerplate\build\extjs

building Ext JS bundle: ext => ...\reactor-typescript-boilerplate\build\extjs
Sencha Cmd v6.2.1.29
[WRN] Failed to download remote catalog : can't parse argument number:
[INF] Loading app json manifest...
[INF] Writing concatenated output to file ...\reactor-typescript-boilerplate\build\extjs\ext.js
[INF] Appending concatenated output to file ...\reactor-typescript-boilerplate\build\extjs\ext.js
[INF] writing sass content to ext.scss
[INF] appending sass content to ext.scss
[INF] appending sass content to ext.scss
[INF] merging 372 input resources into ...\reactor-typescript-boilerplate\build\extjs\resources
[INF] merged 371 resources into ...\reactor-typescript-boilerplate\build\extjs\resources
[INF] merging 6 input resources into ...\reactor-typescript-boilerplate\build\extjs\resources
[INF] merged 6 resources into ...\reactor-typescript-boilerplate\build\extjs\resources
[LOG] Building .../reactor-typescript-boilerplate/build/extjs/ext.scss
webpack: wait until bundle finished: /
Exiting with code 0
[INF] Waiting for changes...
Error: Chunk.initial was removed. Use isInitial()
    at Chunk.set initial [as initial] (...\reactor-typescript-boilerplate\node_modules\webpack\lib\Chunk.js:53:9)
    at ...\reactor-typescript-boilerplate\node_modules\reactor-webpack-ts-plugin\dist\index.js:90:33
    at process._tickCallback (internal/process/next_tick.js:103:7)
webpack: wait until bundle finished: /
```

**Comment by markbrocato** [comment]
Looks like @unional hasn't published the latest webpack plugin to npm yet.

**Comment by unional** [comment]
HI sorry for the delay. Got caught up with something. 
the plugin and this boilerplate is updated.

**Comment by ak99372** [comment]
Hi,

not sure if this is related I got the latest version and get this error on start: 

 ````
 88% chunk assets processing
 89% additional chunk assets processing
 94% asset optimization
building Ext JS bundle: ext => C:\Work\_projects\JavaScript\reactor-typescript-boilerplate-master\build\extjs
events.js:160
      throw er; // Unhandled 'error' event

Error: spawn sencha ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)`
```

**Comment by unional** [comment]
Do you have sencha cmd installed?

**Comment by ak99372** [comment]
Thanks for fast respose @unional reinstalling sencha cmd fixed the above issue.

**Comment by unional** [comment]
Seems like the latest working is working. Closing.

Feel free to let me know if you encounter other issues.
